### ISSUE TITLE
Add CI/CD usable configuration

### ISSUE THREAD

**Issue by paulkramme** [xor-gate/debpkg#1]
At the moment i use GitLab CI, which allows me to execute bash commands on an automated frequency. For this, i have to set the current version via costum CI variables, as i only deploy on tags.

Would i be possible to set the version in an argument, like `version=v0.1`?  

It would really help, because i wouldnt have to use a costum written tool, which takes the variable as an argument, removes the "v" and creates `DEBIAN/control` with the version.

You can see what i mean in my CI config on my [git server](https://git.paukra.com/open-source/btsoot/blob/master/.gitlab-ci.yml).

**Comment by xor-gate** [comment]
I think it should be fearly easy to add a reader for a environment variable like:

```
DEBPKG_VERSION=v0.1 debpkg -c debpkg.yml
```

Is that what you mean?

**Comment by paulkramme** [comment]
Yes, i think thats it. Today i will try to integrate debpkg into my
projects.

Something else: Could you look at my PR at deb-simple?
